steps:
  - name: docker.io/docker:19.03.8
    args:
      - image
      - build
      - --pull
      - --build-arg
      - GOLANG_VERSION=1.14
      - --build-arg
      - ALPINE_VERSION=3.11
      - --target
      - glide
      - -t
      - gcr.io/$PROJECT_ID/cloud-builders/glide:latest
      - .

images:
  - gcr.io/$PROJECT_ID/cloud-builders/glide:latest

timeout: 600s
