steps:
  - name: docker.io/docker:19.03.8
    args:
      - image
      - build
      - --pull
      - --build-arg
      - GOLANG_VERSION=1.14
      - --build-arg
      - ALPINE_VERSION=3.11
      - -t
      - gcr.io/$PROJECT_ID/cloud-builders/go-cloud-debug-agent:$_TAG
      - .
  - name: docker.io/docker:19.03.8
    args:
      - image
      - tag
      - gcr.io/$PROJECT_ID/cloud-builders/go-cloud-debug-agent:$_TAG
      - gcr.io/$PROJECT_ID/cloud-builders/go-cloud-debug-agent:latest

images:
  - gcr.io/$PROJECT_ID/cloud-builders/go-cloud-debug-agent:$_TAG
  - gcr.io/$PROJECT_ID/cloud-builders/go-cloud-debug-agent:latest

timeout: 600s
